apiVersion: v1
kind: Namespace
metadata:
  name: kcloud-dev
  labels:
    name: kcloud-dev
    environment: development
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kcloud-dev-quota
  namespace: kcloud-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "2"
