apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcloud-infra
spec:
  template:
    spec:
      containers:
      - name: kcloud-infra
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: ENVIRONMENT
          value: "production"
