apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kcloud-prod

namePrefix: prod-

commonLabels:
  environment: production

bases:
- ../../base

replicas:
- name: kcloud-infra
  count: 3

images:
- name: kcloud-infra
  newTag: v1.0.0

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: kcloud-infra-config
  behavior: merge
  literals:
  - LOG_LEVEL=info
  - WORKERS=8
  - MAX_CONNECTIONS=200
