apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kcloud

commonLabels:
  app.kubernetes.io/name: kcloud-infra
  app.kubernetes.io/component: infrastructure
  app.kubernetes.io/managed-by: kustomize

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- servicemonitor.yaml
- prometheusrule.yaml

images:
- name: kcloud-infra
  newTag: latest
