apiVersion: v1
kind: Namespace
metadata:
  name: kcloud
  labels:
    name: kcloud
    app.kubernetes.io/managed-by: kustomize
    environment: base
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kcloud-quota
  namespace: kcloud
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "5"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kcloud-limits
  namespace: kcloud
spec:
  limits:
  - max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 250m
      memory: 256Mi
    type: Pod
