apiVersion: v1
kind: Secret
metadata:
  name: kcloud-infra-secrets
  labels:
    app: kcloud-infra
    component: infrastructure
type: Opaque
stringData:
  # OpenStack credentials (replace with actual values)
  OS_AUTH_URL: "http://controller:5000/v3"
  OS_PROJECT_NAME: "kcloud"
  OS_USERNAME: "admin"
  OS_PASSWORD: "changeme"

  # Database credentials (replace with actual values)
  POSTGRES_PASSWORD: "changeme"

  # Redis credentials (replace with actual values)
  REDIS_PASSWORD: "changeme"

  # API keys (replace with actual values)
  SECRET_KEY: "changeme-generate-random-key"
