apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcloud-infra
  labels:
    app: kcloud-infra
    component: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kcloud-infra
  labels:
    app: kcloud-infra
    component: infrastructure
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kcloud-infra
  labels:
    app: kcloud-infra
    component: infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kcloud-infra
subjects:
- kind: ServiceAccount
  name: kcloud-infra
