apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kcloud-infra
  labels:
    app: kcloud-infra
    component: infrastructure
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: kcloud-infra
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      targetLabel: app
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kcloud-infra
  labels:
    app: kcloud-infra
    component: infrastructure
spec:
  selector:
    matchLabels:
      app: kcloud-infra
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 30s
